services:
  api:
    build: 
      context: ./peachme_fastapi
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./peachme_fastapi/main.py:/app/main.py
      - ./peachme_fastapi/app:/app/app
      - ./peachme_fastapi/media:/app/media
      - ./.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - CORS_ORIGINS=${CORS_ORIGINS}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    command: npm run dev
    depends_on:
      - api 