version: '3.8'

services:
  api:
    build: 
      context: ./peachme_fastapi
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./peachme_fastapi/media:/app/media
      - ./peachme_fastapi/peachme.db:/app/peachme.db
      - ./.env:/app/.env
      - ./peachme_fastapi:/app  # Mount the code for hot reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api 